FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/company_review/
RUN mkdir ./static
RUN mkdir ./media

RUN apt-get update 
RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

RUN pip install --upgrade pip
RUN pip install poetry
COPY ./poetry.lock .
COPY ./pyproject.toml .

RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

COPY . .