version: '3.8'
services:
  ###########################
  web:
    container_name: web
    build:
      context: ./company_review
      dockerfile: Dockerfile/Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000
    env_file:
      - ./.env/.env.prod
    volumes:
      - static:/usr/src/company_review/static
      - media:/usr/src/company_review/media
    depends_on:
      - nginx-proxy
  ###########################
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/etc/redis_data/data
    depends_on:
      - web
  ###########################
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - static:/usr/src/company_review/static
      - media:/usr/src/company_review/media
  ###########################
  # nginx-proxy-acme:
  #   container_name: nginx-proxy-acme
  #   image: nginxproxy/acme-companion
  #   volumes:
  #     - certs:/etc/nginx/certs
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - acme:/etc/acme.sh
  #   env_file:
  #     - ./.env/.env.prod.nginx_acme
  #   depends_on:
  #     - nginx-proxy
  ###########################
volumes:
  redis_data:
  certs:
  vhost:
  html:
  acme:
  static:
  media:

