# Generated by Django 4.0.1 on 2022-01-29 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KreditJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('company_pk', models.CharField(max_length=100)),
                ('company_base_content', models.JSONField()),
                ('company_info_data', models.JSONField()),
                ('company_jobdam', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='jobplanet',
            old_name='page',
            new_name='company_pk',
        ),
        migrations.AddField(
            model_name='jobplanet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobplanet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
