# Generated by Django 4.0.1 on 2022-01-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_kreditjob_rename_page_jobplanet_company_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kreditjob',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
