# Generated by Django 4.0.1 on 2022-01-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0005_alter_jobplanet_company_pk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saramin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('company_pk', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
