# Generated by Django 4.0.1 on 2022-02-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0006_saramin'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobplanet',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobplanet',
            name='search_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kreditjob',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kreditjob',
            name='search_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='saramin',
            name='search_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobplanet',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='saramin',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
