# Generated by Django 4.0.1 on 2022-02-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0007_jobplanet_address_jobplanet_search_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobplanet',
            name='search_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='kreditjob',
            name='search_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='saramin',
            name='search_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
