# Generated by Django 4.0.1 on 2022-02-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0009_jobkorea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobkorea',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='jobplanet',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='kreditjob',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='saramin',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
