# Generated by Django 4.0.1 on 2022-02-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0010_alter_jobkorea_address_alter_jobplanet_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('search_q', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
